# This workflow is an example of DevOps practices applied in daily testing.
# The main feature of this WorkFlow is Figlet, an ascii art on these executions.

# ===============================================
# Yo can see some of my skills on my sites:      |
# https://www.linkedin.com/in/arodriguezfarias/  |
# https://rodriguezfarias.com/                   |
# ==============================================

name: QA Engineer | Antonio Rodriguez Farias

on:
  schedule:
    - cron: '*/15 * * * *'
  # workflow_dispatch:

jobs:
  test_figlet:
    if: github.event.schedule == '*/15 * * * *'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    defaults:
      run:
        working-directory: Jenkins-CI
    env:
      GH_TOKEN: ${{ secrets.PAT }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install & Run Figlet
        id: installFiglet
        if: always()
        run: |
          sudo apt install -y figlet
          figlet -c Antonio Rodriguez > file.txt
          date >> file.txt

      - name: Date
        run: echo "DATE=$(date +'%H%M-%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload Figlet File
        id: uploadFile
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ env.DATE }}
          path: Jenkins-CI/file.txt

       
      - name: Push to Repo
        uses: actions-x/commit@v6
        with:
          email: abgrodriguezfarias@gmail.com
          name: Antonio Rodriguez Farias
          message: QA Engineer | Antonio Rodriguez Farias
          branch: main
          files: file.txt
          repository: https://github.com/AntoniHub/Selenium-QA.git
          token: ${{ secrets.PAT }}
          force: true
          directory: "Jenkins-CI"
